In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [12]:
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [13]:
a.ndim

2

In [14]:
a=np.array([1,2,3])

In [15]:
a.size

3

In [16]:
a.nbytes

12

In [17]:
a.ndim

1

In [18]:
a.itemsize

4

In [36]:
#numpy vs list -> memory

import sys

l=list(range(1000))
a=np.arange(1000,dtype=np.int8)
print("LIST  SIZE:",sys.getsizeof(list(range(1000))))
print("NUMPY SIZE:",sys.getsizeof(a))


LIST  SIZE: 8056
NUMPY SIZE: 1096


In [24]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [27]:
import time
l1=list(range(100000))
l2=list(range(100000))

a1=np.arange(100000,dtype=np.np.int8)
a2=np.arange(100000,dtype=np.np.int8)
start=time.time()
[x+y for x,y in zip(l1,l2)]
end=time.time()
print((end-start)*1000)

start=time.time()
a1+a2
end=time.time()
print((end-start)*1000)

7.824182510375977
0.9968280792236328


In [32]:
a=np.array([1,2,3],dtype=np.int8)

In [33]:
a.itemsize

1

In [37]:
a=np.array([(1,2,3),(4,5,6)])
a.shape

(2, 3)

In [38]:
print(a)

[[1 2 3]
 [4 5 6]]


In [39]:
a=a.reshape(3,2)

In [40]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [41]:
a=np.array([(1,2,3),(4,5,6)])


In [42]:
print(a[0,2])

3


In [43]:
print(a[0:,2])

[3 6]


In [45]:
print(a[1,0:])

[4 5 6]


In [46]:
a.min()

1

In [47]:
a.max()

6

In [48]:
a.sum()

21

In [49]:
print(a)

[[1 2 3]
 [4 5 6]]


In [50]:
print(a.sum(axis=0))

[5 7 9]


In [51]:
print(a.sum(axis=1))

[ 6 15]


In [52]:
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [53]:
print(np.std(a))

1.707825127659933


In [54]:
print(np.sin(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [55]:
print(np.cos(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [57]:
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3),(4,5,6)])
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [58]:
a-b

array([[0, 0, 0],
       [0, 0, 0]])

In [59]:
a.shape

(2, 3)

In [62]:
b=b.reshape(3,2)

In [64]:
b.shape

(3, 2)

In [65]:
np.dot(a,b)

array([[22, 28],
       [49, 64]])

In [66]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
a+2

array([[3, 4, 5],
       [6, 7, 8]])

In [68]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
np.full((3,3),11)

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [73]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [76]:
import math

In [77]:
math.e

2.718281828459045

In [78]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [80]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [81]:
a.ndim

3

In [82]:
a[0,1,1]

4

In [86]:
a[1,1,0]

7

In [93]:
list1=[1,2,3]
list2=[4,5,6]

#[expr for x in values if cond]

[(x,y) for x in list1 for y in list2]

[(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)]